paths:
  root_dir: "audio_files"
  output_dir: "audio_sentences"
  text_subdir: "text_sentences"
  temp_dir: "temp_files"
  
  

vad:
  aggressiveness: 2          # 0-3
  min_silence_ms: 1000         # milliseconds
  sample_rate: 16000
  resample: True
  silence_threshold: 0.01
  frame_duration: 30.0
  file_foramt: "wav"

processing:
  min_len: 0.0
  segment_name: "segment_"

silence_trim:
  threshold: 0.05
  window_ms: 20

csv:
  split_info_filename: "split_info.csv"
  metrics_filename: "reading_metrics.csv"