
paths:
  root_dir: "data/wavs_20250416_012741"
  output_dir: "data/wavs_20250416_012741_splits"
  temp_dir: "temp"

vad:
  aggressiveness: 2  # 0-3
  min_silence_ms: 400
  min_segment_ms: 1000
  sample_rate: 16000
  resample: True
  frame_duration: 30
  file_format: "wav"

processing:
  min_len: 0.0
  segment_name: "segment"
  max_workers: 8
  segment_subfolders: True
  batch_size: 10