data:
  root_dir: "Recording_251114"  # Root directory containing folders with .wav and .txt
  folder_prefix: null             # optional; only process folders starting with this prefix
  nested_folders: True               # optional prefix for outputs

val:
  ratio_threshold: 0.25                # max allowed word count difference ratio between predicted and reference
  val_csv_output: "validation_summary.csv"  # CSV file name to save validation results
  delete_files: True
